# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ghada-hajji/Téléchargements/codeprojet/Detection-de-collisions-3D-de-drones-avec-chiffrement-homomorphe-batching

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ghada-hajji/Téléchargements/codeprojet/Detection-de-collisions-3D-de-drones-avec-chiffrement-homomorphe-batching

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ghada-hajji/Téléchargements/codeprojet/Detection-de-collisions-3D-de-drones-avec-chiffrement-homomorphe-batching/CMakeFiles /home/ghada-hajji/Téléchargements/codeprojet/Detection-de-collisions-3D-de-drones-avec-chiffrement-homomorphe-batching//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ghada-hajji/Téléchargements/codeprojet/Detection-de-collisions-3D-de-drones-avec-chiffrement-homomorphe-batching/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named drone_collision

# Build rule for target.
drone_collision: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 drone_collision
.PHONY : drone_collision

# fast build rule for target.
drone_collision/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_collision.dir/build.make CMakeFiles/drone_collision.dir/build
.PHONY : drone_collision/fast

#=============================================================================
# Target rules for targets named test_geometry_clear

# Build rule for target.
test_geometry_clear: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_geometry_clear
.PHONY : test_geometry_clear

# fast build rule for target.
test_geometry_clear/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_geometry_clear.dir/build.make CMakeFiles/test_geometry_clear.dir/build
.PHONY : test_geometry_clear/fast

#=============================================================================
# Target rules for targets named test_fhe_oracle

# Build rule for target.
test_fhe_oracle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_fhe_oracle
.PHONY : test_fhe_oracle

# fast build rule for target.
test_fhe_oracle/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fhe_oracle.dir/build.make CMakeFiles/test_fhe_oracle.dir/build
.PHONY : test_fhe_oracle/fast

#=============================================================================
# Target rules for targets named test_benchmark_scalability

# Build rule for target.
test_benchmark_scalability: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_benchmark_scalability
.PHONY : test_benchmark_scalability

# fast build rule for target.
test_benchmark_scalability/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_benchmark_scalability.dir/build.make CMakeFiles/test_benchmark_scalability.dir/build
.PHONY : test_benchmark_scalability/fast

src/engine.o: src/engine.cpp.o
.PHONY : src/engine.o

# target to build an object file
src/engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_collision.dir/build.make CMakeFiles/drone_collision.dir/src/engine.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_geometry_clear.dir/build.make CMakeFiles/test_geometry_clear.dir/src/engine.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fhe_oracle.dir/build.make CMakeFiles/test_fhe_oracle.dir/src/engine.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_benchmark_scalability.dir/build.make CMakeFiles/test_benchmark_scalability.dir/src/engine.cpp.o
.PHONY : src/engine.cpp.o

src/engine.i: src/engine.cpp.i
.PHONY : src/engine.i

# target to preprocess a source file
src/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_collision.dir/build.make CMakeFiles/drone_collision.dir/src/engine.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_geometry_clear.dir/build.make CMakeFiles/test_geometry_clear.dir/src/engine.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fhe_oracle.dir/build.make CMakeFiles/test_fhe_oracle.dir/src/engine.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_benchmark_scalability.dir/build.make CMakeFiles/test_benchmark_scalability.dir/src/engine.cpp.i
.PHONY : src/engine.cpp.i

src/engine.s: src/engine.cpp.s
.PHONY : src/engine.s

# target to generate assembly for a file
src/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_collision.dir/build.make CMakeFiles/drone_collision.dir/src/engine.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_geometry_clear.dir/build.make CMakeFiles/test_geometry_clear.dir/src/engine.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fhe_oracle.dir/build.make CMakeFiles/test_fhe_oracle.dir/src/engine.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_benchmark_scalability.dir/build.make CMakeFiles/test_benchmark_scalability.dir/src/engine.cpp.s
.PHONY : src/engine.cpp.s

src/geometry.o: src/geometry.cpp.o
.PHONY : src/geometry.o

# target to build an object file
src/geometry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_collision.dir/build.make CMakeFiles/drone_collision.dir/src/geometry.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_geometry_clear.dir/build.make CMakeFiles/test_geometry_clear.dir/src/geometry.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fhe_oracle.dir/build.make CMakeFiles/test_fhe_oracle.dir/src/geometry.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_benchmark_scalability.dir/build.make CMakeFiles/test_benchmark_scalability.dir/src/geometry.cpp.o
.PHONY : src/geometry.cpp.o

src/geometry.i: src/geometry.cpp.i
.PHONY : src/geometry.i

# target to preprocess a source file
src/geometry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_collision.dir/build.make CMakeFiles/drone_collision.dir/src/geometry.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_geometry_clear.dir/build.make CMakeFiles/test_geometry_clear.dir/src/geometry.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fhe_oracle.dir/build.make CMakeFiles/test_fhe_oracle.dir/src/geometry.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_benchmark_scalability.dir/build.make CMakeFiles/test_benchmark_scalability.dir/src/geometry.cpp.i
.PHONY : src/geometry.cpp.i

src/geometry.s: src/geometry.cpp.s
.PHONY : src/geometry.s

# target to generate assembly for a file
src/geometry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_collision.dir/build.make CMakeFiles/drone_collision.dir/src/geometry.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_geometry_clear.dir/build.make CMakeFiles/test_geometry_clear.dir/src/geometry.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fhe_oracle.dir/build.make CMakeFiles/test_fhe_oracle.dir/src/geometry.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_benchmark_scalability.dir/build.make CMakeFiles/test_benchmark_scalability.dir/src/geometry.cpp.s
.PHONY : src/geometry.cpp.s

src/intersection.o: src/intersection.cpp.o
.PHONY : src/intersection.o

# target to build an object file
src/intersection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_collision.dir/build.make CMakeFiles/drone_collision.dir/src/intersection.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fhe_oracle.dir/build.make CMakeFiles/test_fhe_oracle.dir/src/intersection.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_benchmark_scalability.dir/build.make CMakeFiles/test_benchmark_scalability.dir/src/intersection.cpp.o
.PHONY : src/intersection.cpp.o

src/intersection.i: src/intersection.cpp.i
.PHONY : src/intersection.i

# target to preprocess a source file
src/intersection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_collision.dir/build.make CMakeFiles/drone_collision.dir/src/intersection.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fhe_oracle.dir/build.make CMakeFiles/test_fhe_oracle.dir/src/intersection.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_benchmark_scalability.dir/build.make CMakeFiles/test_benchmark_scalability.dir/src/intersection.cpp.i
.PHONY : src/intersection.cpp.i

src/intersection.s: src/intersection.cpp.s
.PHONY : src/intersection.s

# target to generate assembly for a file
src/intersection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_collision.dir/build.make CMakeFiles/drone_collision.dir/src/intersection.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fhe_oracle.dir/build.make CMakeFiles/test_fhe_oracle.dir/src/intersection.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_benchmark_scalability.dir/build.make CMakeFiles/test_benchmark_scalability.dir/src/intersection.cpp.s
.PHONY : src/intersection.cpp.s

src/io.o: src/io.cpp.o
.PHONY : src/io.o

# target to build an object file
src/io.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_collision.dir/build.make CMakeFiles/drone_collision.dir/src/io.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_geometry_clear.dir/build.make CMakeFiles/test_geometry_clear.dir/src/io.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fhe_oracle.dir/build.make CMakeFiles/test_fhe_oracle.dir/src/io.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_benchmark_scalability.dir/build.make CMakeFiles/test_benchmark_scalability.dir/src/io.cpp.o
.PHONY : src/io.cpp.o

src/io.i: src/io.cpp.i
.PHONY : src/io.i

# target to preprocess a source file
src/io.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_collision.dir/build.make CMakeFiles/drone_collision.dir/src/io.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_geometry_clear.dir/build.make CMakeFiles/test_geometry_clear.dir/src/io.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fhe_oracle.dir/build.make CMakeFiles/test_fhe_oracle.dir/src/io.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_benchmark_scalability.dir/build.make CMakeFiles/test_benchmark_scalability.dir/src/io.cpp.i
.PHONY : src/io.cpp.i

src/io.s: src/io.cpp.s
.PHONY : src/io.s

# target to generate assembly for a file
src/io.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_collision.dir/build.make CMakeFiles/drone_collision.dir/src/io.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_geometry_clear.dir/build.make CMakeFiles/test_geometry_clear.dir/src/io.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fhe_oracle.dir/build.make CMakeFiles/test_fhe_oracle.dir/src/io.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_benchmark_scalability.dir/build.make CMakeFiles/test_benchmark_scalability.dir/src/io.cpp.s
.PHONY : src/io.cpp.s

src/main_centralisée.o: src/main_centralisée.cpp.o
.PHONY : src/main_centralisée.o

# target to build an object file
src/main_centralisée.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_collision.dir/build.make CMakeFiles/drone_collision.dir/src/main_centralisée.cpp.o
.PHONY : src/main_centralisée.cpp.o

src/main_centralisée.i: src/main_centralisée.cpp.i
.PHONY : src/main_centralisée.i

# target to preprocess a source file
src/main_centralisée.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_collision.dir/build.make CMakeFiles/drone_collision.dir/src/main_centralisée.cpp.i
.PHONY : src/main_centralisée.cpp.i

src/main_centralisée.s: src/main_centralisée.cpp.s
.PHONY : src/main_centralisée.s

# target to generate assembly for a file
src/main_centralisée.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drone_collision.dir/build.make CMakeFiles/drone_collision.dir/src/main_centralisée.cpp.s
.PHONY : src/main_centralisée.cpp.s

tests/test_benchmark_scalability.o: tests/test_benchmark_scalability.cpp.o
.PHONY : tests/test_benchmark_scalability.o

# target to build an object file
tests/test_benchmark_scalability.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_benchmark_scalability.dir/build.make CMakeFiles/test_benchmark_scalability.dir/tests/test_benchmark_scalability.cpp.o
.PHONY : tests/test_benchmark_scalability.cpp.o

tests/test_benchmark_scalability.i: tests/test_benchmark_scalability.cpp.i
.PHONY : tests/test_benchmark_scalability.i

# target to preprocess a source file
tests/test_benchmark_scalability.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_benchmark_scalability.dir/build.make CMakeFiles/test_benchmark_scalability.dir/tests/test_benchmark_scalability.cpp.i
.PHONY : tests/test_benchmark_scalability.cpp.i

tests/test_benchmark_scalability.s: tests/test_benchmark_scalability.cpp.s
.PHONY : tests/test_benchmark_scalability.s

# target to generate assembly for a file
tests/test_benchmark_scalability.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_benchmark_scalability.dir/build.make CMakeFiles/test_benchmark_scalability.dir/tests/test_benchmark_scalability.cpp.s
.PHONY : tests/test_benchmark_scalability.cpp.s

tests/test_fhe_oracle.o: tests/test_fhe_oracle.cpp.o
.PHONY : tests/test_fhe_oracle.o

# target to build an object file
tests/test_fhe_oracle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fhe_oracle.dir/build.make CMakeFiles/test_fhe_oracle.dir/tests/test_fhe_oracle.cpp.o
.PHONY : tests/test_fhe_oracle.cpp.o

tests/test_fhe_oracle.i: tests/test_fhe_oracle.cpp.i
.PHONY : tests/test_fhe_oracle.i

# target to preprocess a source file
tests/test_fhe_oracle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fhe_oracle.dir/build.make CMakeFiles/test_fhe_oracle.dir/tests/test_fhe_oracle.cpp.i
.PHONY : tests/test_fhe_oracle.cpp.i

tests/test_fhe_oracle.s: tests/test_fhe_oracle.cpp.s
.PHONY : tests/test_fhe_oracle.s

# target to generate assembly for a file
tests/test_fhe_oracle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fhe_oracle.dir/build.make CMakeFiles/test_fhe_oracle.dir/tests/test_fhe_oracle.cpp.s
.PHONY : tests/test_fhe_oracle.cpp.s

tests/test_geometry_clear.o: tests/test_geometry_clear.cpp.o
.PHONY : tests/test_geometry_clear.o

# target to build an object file
tests/test_geometry_clear.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_geometry_clear.dir/build.make CMakeFiles/test_geometry_clear.dir/tests/test_geometry_clear.cpp.o
.PHONY : tests/test_geometry_clear.cpp.o

tests/test_geometry_clear.i: tests/test_geometry_clear.cpp.i
.PHONY : tests/test_geometry_clear.i

# target to preprocess a source file
tests/test_geometry_clear.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_geometry_clear.dir/build.make CMakeFiles/test_geometry_clear.dir/tests/test_geometry_clear.cpp.i
.PHONY : tests/test_geometry_clear.cpp.i

tests/test_geometry_clear.s: tests/test_geometry_clear.cpp.s
.PHONY : tests/test_geometry_clear.s

# target to generate assembly for a file
tests/test_geometry_clear.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_geometry_clear.dir/build.make CMakeFiles/test_geometry_clear.dir/tests/test_geometry_clear.cpp.s
.PHONY : tests/test_geometry_clear.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... drone_collision"
	@echo "... test_benchmark_scalability"
	@echo "... test_fhe_oracle"
	@echo "... test_geometry_clear"
	@echo "... src/engine.o"
	@echo "... src/engine.i"
	@echo "... src/engine.s"
	@echo "... src/geometry.o"
	@echo "... src/geometry.i"
	@echo "... src/geometry.s"
	@echo "... src/intersection.o"
	@echo "... src/intersection.i"
	@echo "... src/intersection.s"
	@echo "... src/io.o"
	@echo "... src/io.i"
	@echo "... src/io.s"
	@echo "... src/main_centralisée.o"
	@echo "... src/main_centralisée.i"
	@echo "... src/main_centralisée.s"
	@echo "... tests/test_benchmark_scalability.o"
	@echo "... tests/test_benchmark_scalability.i"
	@echo "... tests/test_benchmark_scalability.s"
	@echo "... tests/test_fhe_oracle.o"
	@echo "... tests/test_fhe_oracle.i"
	@echo "... tests/test_fhe_oracle.s"
	@echo "... tests/test_geometry_clear.o"
	@echo "... tests/test_geometry_clear.i"
	@echo "... tests/test_geometry_clear.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

